apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: online-boutique
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Online Boutique applications managed through GitOps on GKE
  sourceRepos:
    - https://github.com/matmajk/devsecops-gitops.git
  destinations:
    - namespace: online-boutique
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
      name: online-boutique
  namespaceResourceWhitelist:
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: ""
      kind: Pod
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount