apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: online-boutique
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Online Boutique applications managed through GitOps
  sourceRepos:
    - https://github.com/matmajk/devsecops-gitops.git
  destinations:
    - namespace: online-boutique
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
