{{- if .Values.adService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "adservice"
      "component" "catalog"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.adService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: adservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "adservice"
          "component" "catalog"
        ) | nindent 8 }}
    spec:
      serviceAccountName: adservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: adservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.adService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.adService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.adService.containerPort | quote }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.adService.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.adService.probes.readiness.periodSeconds }}
            grpc:
              port: {{ .Values.adService.containerPort }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.adService.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.adService.probes.liveness.periodSeconds }}
            grpc:
              port: {{ .Values.adService.containerPort }}
          resources:
            {{- toYaml .Values.adService.resources | nindent 12 }}
{{- end }}
