{{- if .Values.adService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "adservice"
      "component" "catalog"
    ) | nindent 4 }}
automountServiceAccountToken: false
# This service account is used by the frontend pod to access other services in the cluster. It does not need a token for external access (e.g., for internal cluster communication).
{{- end }}
