{{- if .Values.cartService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "cartservice"
      "component" "cart"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.cartService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cartservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "cartservice"
          "component" "cart"
        ) | nindent 8 }}
    spec:
      serviceAccountName: cartservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: cartservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.cartService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.cartService.containerPort }}
              protocol: TCP
          env:
            - name: REDIS_ADDR
              value: {{ .Values.cartService.dependencies.redis | quote }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.cartService.probes.readiness.initialDelaySeconds }}
            grpc:
              port: {{ .Values.cartService.containerPort }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.cartService.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.cartService.probes.liveness.periodSeconds }}
            grpc:
              port: {{ .Values.cartService.containerPort }}
          resources:
            {{- toYaml .Values.cartService.resources | nindent 12 }}
{{- end }}
