{{- if .Values.checkoutService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "checkoutservice"
      "component" "checkout"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.checkoutService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: checkoutservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "checkoutservice"
          "component" "checkout"
        ) | nindent 8 }}
    spec:
      serviceAccountName: checkoutservice
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: checkoutservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.checkoutService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.checkoutService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.checkoutService.containerPort | quote }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.productCatalogService | quote }}
            - name: SHIPPING_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.shippingService | quote }}
            - name: PAYMENT_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.paymentService | quote }}
            - name: EMAIL_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.emailService | quote }}
            - name: CURRENCY_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.currencyService | quote }}
            - name: CART_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.cartService | quote }}
          readinessProbe:
            grpc:
              port: {{ .Values.checkoutService.containerPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.checkoutService.containerPort }}
          resources:
            {{- toYaml .Values.checkoutService.resources | nindent 12 }}
{{- end }}
