{{- if .Values.checkoutService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
    app.kubernetes.io/name: checkoutservice
    app.kubernetes.io/component: checkout
spec:
  replicas: {{ .Values.checkoutService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: checkoutservice
  template:
    metadata:
      labels:
        app.kubernetes.io/name: checkoutservice
        app.kubernetes.io/component: checkout
        app.kubernetes.io/part-of: online-boutique
    spec:
      serviceAccountName: checkoutservice
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: checkoutservice
          image: "{{ .Values.global.imageRepository }}/{{ .Values.checkoutService.image.name }}:{{ .Values.global.imageTag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: grpc
              containerPort: {{ .Values.checkoutService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.checkoutService.containerPort | quote }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.productCatalogService | quote }}
            - name: SHIPPING_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.shippingService | quote }}
            - name: PAYMENT_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.paymentService | quote }}
            - name: EMAIL_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.emailService | quote }}
            - name: CURRENCY_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.currencyService | quote }}
            - name: CART_SERVICE_ADDR
              value: {{ .Values.checkoutService.dependencies.cartService | quote }}
          readinessProbe:
            grpc:
              port: {{ .Values.checkoutService.containerPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.checkoutService.containerPort }}
          resources:
            {{- toYaml .Values.checkoutService.resources | nindent 12 }}
{{- end }}
