{{- if .Values.currencyService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "currencyservice"
      "component" "catalog"
    ) | nindent 4 }}
spec:
  type: {{ .Values.currencyService.service.type }}
  selector:
    app.kubernetes.io/name: currencyservice
  ports:
    - name: grpc
      port: {{ .Values.currencyService.service.port }}
      targetPort: {{ .Values.currencyService.service.targetPort }}
      protocol: TCP
{{- end }}
