{{- if .Values.currencyService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: currencyservice
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
    app.kubernetes.io/name: currencyservice
    app.kubernetes.io/component: catalog
automountServiceAccountToken: false
# This service account is used by the frontend pod to access other services in the cluster. It does not need a token for external access (e.g., for internal cluster communication).
{{- end }}
