{{- if .Values.currencyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "currencyservice"
      "component" "catalog"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.currencyService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: currencyservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "currencyservice"
          "component" "catalog"
        ) | nindent 8 }}
    spec:
      serviceAccountName: currencyservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: currencyservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.currencyService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.currencyService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.currencyService.containerPort | quote }}
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: {{ .Values.currencyService.containerPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.currencyService.containerPort }}
          resources:
            {{- toYaml .Values.currencyService.resources | nindent 12 }}
{{- end }}
