{{- if .Values.emailService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "emailservice"
      "component" "email"
    ) | nindent 4 }}
spec:
  type: {{ .Values.emailService.service.type }}
  selector:
    app.kubernetes.io/name: emailservice
  ports:
    - name: grpc
      port: {{ .Values.emailService.service.port }}
      targetPort: {{ .Values.emailService.service.targetPort }}
      protocol: TCP
{{- end }}
