{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "frontend"
      "component" "frontend"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "frontend"
          "component" "frontend"
        ) | nindent 8 }}
    spec:
      serviceAccountName: frontend
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: frontend
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.frontend.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.frontend.containerPort | quote }}
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.productCatalogService | quote }}
            - name: CURRENCY_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.currencyService | quote }}
            - name: CART_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.cartService | quote }}
            - name: RECOMMENDATION_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.recommendationService | quote }}
            - name: SHIPPING_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.shippingService | quote }}
            - name: CHECKOUT_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.checkoutService | quote }}
            - name: AD_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.adService | quote }}
            - name: SHOPPING_ASSISTANT_SERVICE_ADDR
              value: {{ .Values.frontend.dependencies.shoppingAssistantService | quote }}
            - name: ENABLE_PROFILER
              value: "0"
          readinessProbe:
            initialDelaySeconds: {{ .Values.frontend.probes.readiness.initialDelaySeconds }}
            httpGet:
              path: /_healthz
              port: http
              httpHeaders:
                - name: Cookie
                  value: "shop_session-id=x-readiness-probe"
          livenessProbe:
            initialDelaySeconds: {{ .Values.frontend.probes.liveness.initialDelaySeconds }}
            httpGet:
              path: /_healthz
              port: http
              httpHeaders:
                - name: Cookie
                  value: "shop_session-id=x-liveness-probe"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
