{{- if .Values.paymentService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: paymentservice
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
    app.kubernetes.io/name: paymentservice
    app.kubernetes.io/component: payment
automountServiceAccountToken: false
# This service account is used by the frontend pod to access other services in the cluster. It does not need a token for external access (e.g., for internal cluster communication).
{{- end }}
