{{- if .Values.paymentService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "paymentservice"
      "component" "payment"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.paymentService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: paymentservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "paymentservice"
          "component" "payment"
        ) | nindent 8 }}
    spec:
      serviceAccountName: paymentservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: paymentservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.paymentService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.paymentService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.paymentService.containerPort | quote }}
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: {{ .Values.paymentService.containerPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.paymentService.containerPort }}
          resources:
            {{- toYaml .Values.paymentService.resources | nindent 12 }}
{{- end }}
