{{- if .Values.productCatalogService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productcatalogservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "productcatalogservice"
      "component" "catalog"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.productCatalogService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: productcatalogservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "productcatalogservice"
          "component" "catalog"
        ) | nindent 8 }}
    spec:
      serviceAccountName: productcatalogservice
      terminationGracePeriodSeconds: 5
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: productcatalogservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.productCatalogService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.productCatalogService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.productCatalogService.containerPort | quote }}
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            grpc:
              port: {{ .Values.productCatalogService.containerPort }}
          livenessProbe:
            grpc:
              port: {{ .Values.productCatalogService.containerPort }}
          resources:
            {{- toYaml .Values.productCatalogService.resources | nindent 12 }}
{{- end }}
