{{- if .Values.recommendationService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "recommendationservice"
      "component" "catalog"
    ) | nindent 4 }}
spec:
  type: {{ .Values.recommendationService.service.type }}
  selector:
    app.kubernetes.io/name: recommendationservice
  ports:
    - name: grpc
      port: {{ .Values.recommendationService.service.port }}
      targetPort: {{ .Values.recommendationService.service.targetPort }}
      protocol: TCP
{{- end }}
