{{- if .Values.redisCart.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    {{- include "online-boutique.labels" . | nindent 4 }}
    app.kubernetes.io/name: redis-cart
    app.kubernetes.io/component: cart-database
spec:
  replicas: {{ .Values.redisCart.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cart
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis-cart
        app.kubernetes.io/component: cart-database
        app.kubernetes.io/part-of: online-boutique
    spec:
      automountServiceAccountToken: false
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: redis
          image: "{{ .Values.redisCart.image.repository }}:{{ .Values.redisCart.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          ports:
            - name: redis
              containerPort: {{ .Values.redisCart.containerPort }}
              protocol: TCP
          readinessProbe:
            periodSeconds: {{ .Values.redisCart.probes.readiness.periodSeconds }}
            tcpSocket:
              port: redis
          livenessProbe:
            periodSeconds: {{ .Values.redisCart.probes.liveness.periodSeconds }}
            tcpSocket:
              port: redis
          resources:
            {{- toYaml .Values.redisCart.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
{{- end }}
