{{- if .Values.redisCart.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-cart
  labels:
    {{- include "online-boutique.componentLabels" (dict 
      "root" . 
      "name" "redis-cart" 
      "component" "cart-database"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.redisCart.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cart
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "redis-cart"
          "component" "cart-database"
        ) | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: redis
          image: "{{ .Values.redisCart.image.repository }}:{{ .Values.redisCart.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: redis
              containerPort: {{ .Values.redisCart.containerPort }}
              protocol: TCP
          readinessProbe:
            periodSeconds: {{ .Values.redisCart.probes.readiness.periodSeconds }}
            tcpSocket:
              port: redis
          livenessProbe:
            periodSeconds: {{ .Values.redisCart.probes.liveness.periodSeconds }}
            tcpSocket:
              port: redis
          resources:
            {{- toYaml .Values.redisCart.resources | nindent 12 }}
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          emptyDir: {}
{{- end }}
