{{- if .Values.redisCart.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-cart
  labels:
    {{- include "online-boutique.componentLabels" (dict 
      "root" . 
      "name" "redis-cart" 
      "component" "cart-database"
    ) | nindent 4 }}
spec:
  type: {{ .Values.redisCart.service.type }}
  selector:
    app.kubernetes.io/name: redis-cart
  ports:
    - name: tcp-redis
      port: {{ .Values.redisCart.service.port }}
      targetPort: {{ .Values.redisCart.service.targetPort }}
      protocol: TCP
{{- end }}
