{{- if .Values.shippingService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
  labels:
    {{- include "online-boutique.componentLabels" (dict
      "root" .
      "name" "shippingservice"
      "component" "shipping"
    ) | nindent 4 }}
spec:
  replicas: {{ .Values.shippingService.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: shippingservice
  template:
    metadata:
      labels:
        {{- include "online-boutique.podLabels" (dict
          "root" .
          "name" "shippingservice"
          "component" "shipping"
        ) | nindent 8 }}
    spec:
      serviceAccountName: shippingservice
      securityContext:
        {{- toYaml .Values.global.podSecurityContext | nindent 8 }}
      containers:
        - name: shippingservice
          image: {{ include "online-boutique.appImage" (dict
            "root" .
            "name" .Values.shippingService.image.name
          ) | quote }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          securityContext:
            {{- toYaml .Values.global.containerSecurityContext | nindent 12 }}
          ports:
            - name: grpc
              containerPort: {{ .Values.shippingService.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.shippingService.containerPort | quote }}
            - name: DISABLE_PROFILER
              value: "1"
          readinessProbe:
            periodSeconds: {{ .Values.shippingService.probes.readiness.periodSeconds }}
            grpc:
              port: {{ .Values.shippingService.containerPort }}
          livenessProbe:
            periodSeconds: {{ .Values.shippingService.probes.liveness.periodSeconds }}
            grpc:
              port: {{ .Values.shippingService.containerPort }}
          resources:
            {{- toYaml .Values.shippingService.resources | nindent 12 }}
{{- end }}
