apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-opentelemetry-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-collector
      targetRevision: 0.172.0
      helm:
        releaseName: opentelemetry-collector
        valueFiles:
          - $values/environments/local/observability/opentelemetry-collector-values.yaml
    - repoURL: https://github.com/matmajk/devsecops-gitops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true