apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-boutique-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: online-boutique
  source:
    repoURL: https://github.com/matmajk/devsecops-gitops.git
    targetRevision: master
    path: applications/online-boutique/chart
    helm:
      releaseName: online-boutique
      valueFiles:
        - ../../../environments/local/online-boutique/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: online-boutique
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true