frontend:
  replicaCount: 1
loadGenerator:
  enabled: false
  users: 12
  rate: 1
productCatalogService:
  replicaCount: 1
  image:
    repository: "host.docker.internal:8082/online-boutique-docker-local"
    tag: "ci-f3fffcbd04a10db677b1717716b8e98006137827"
  imagePullSecrets:
    - name: jfrog-registry
