defaults:
  automatedEnvironment: local

services:
  productcatalogservice:
    valuesKey: productCatalogService
    workloadName: productcatalogservice
    containerName: productcatalogservice

environments:
  local:
    valuesFile: environments/local/online-boutique/values.yaml
    chartPath: applications/online-boutique/chart
    namespace: online-boutique