global:
  tracing:
    enabled: false
productCatalogService:
  image:
    name: productcatalogservice
    repository: europe-central2-docker.pkg.dev/devsecops-portfolio-matmajk/online-boutique
    tag: "ci-a939e885f27b6b3d01f403e0f76f844622cf7f02"
  imagePullSecrets: []
loadGenerator:
  enabled: false
