global:
  tracing:
    enabled: false

productCatalogService:
  image:
    name: productcatalogservice
    repository: europe-central2-docker.pkg.dev/devsecops-portfolio-matmajk/online-boutique
    tag: "ci-878f49e73f60fdcf334c841aa4b748259aef7b08"
  imagePullSecrets: []

loadGenerator:
  enabled: false