frontend:
  replicaCount: 1
loadGenerator:
  enabled: false
  users: 12
  rate: 1
productCatalogService:
  replicaCount: 1
  image:
    repository: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo
    tag: v0.10.6
  imagePullSecrets: []
