apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-metrics-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 89.2.2
      helm:
        releaseName: kube-prometheus-stack
        valueFiles:
          - $values/environments/local/observability/kube-prometheus-stack-values.yaml
    - repoURL: https://github.com/matmajk/devsecops-gitops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true