apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-loki-local
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: observability
  sources:
    - repoURL: https://grafana-community.github.io/helm-charts
      chart: loki
      targetRevision: 18.12.1
      helm:
        releaseName: loki
        valueFiles:
          - $values/environments/local/observability/loki-values.yaml
    - repoURL: https://github.com/matmajk/devsecops-gitops.git
      targetRevision: master
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ServerSideApply=true