global:
  imageRepository: us-central1-docker.pkg.dev/online-boutique-ci/microservices-demo
  imageTag: 'v0.10.6'
  imagePullPolicy: IfNotPresent
  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
  containerSecurityContext:
    allowPrivilegeEscalation: false
    privileged: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - ALL

frontend:
  enabled: true
  image:
    name: frontend
  replicaCount: 1
  containerPort: 8080
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
  probes:
    readiness:
      initialDelaySeconds: 10
    liveness:
      initialDelaySeconds: 10
  dependencies:
    productCatalogService: 'productcatalogservice:3550'
    currencyService: 'currencyservice:7000'
    cartService: 'cartservice:7070'
    recommendationService: 'recommendationservice:8080'
    shippingService: 'shippingservice:50051'
    checkoutService: 'checkoutservice:5050'
    adService: 'adservice:9555'
    shoppingAssistantService: 'shoppingassistantservice:80'

productCatalogService:
  enabled: true
  image:
    name: productcatalogservice
  replicaCount: 1
  containerPort: 3550
  service:
    type: ClusterIP
    port: 3550
    targetPort: 3550
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

currencyService:
  enabled: true
  image:
    name: currencyservice
  replicaCount: 1
  containerPort: 7000
  service:
    type: ClusterIP
    port: 7000
    targetPort: 7000
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

recommendationService:
  enabled: true
  image:
    name: recommendationservice
  replicaCount: 1
  containerPort: 8080
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
  dependencies:
    productCatalogService: 'productcatalogservice:3550'
  resources:
    requests:
      cpu: 100m
      memory: 220Mi
    limits:
      cpu: 200m
      memory: 450Mi

adService:
  enabled: true
  image:
    name: adservice
  replicaCount: 1
  containerPort: 9555
  service:
    type: ClusterIP
    port: 9555
    targetPort: 9555
  probes:
    readiness:
      initialDelaySeconds: 20
      periodSeconds: 15
    liveness:
      initialDelaySeconds: 20
      periodSeconds: 15
  resources:
    requests:
      cpu: 200m
      memory: 180Mi
    limits:
      cpu: 300m
      memory: 300Mi

redisCart:
  enabled: true
  image:
    repository: redis
    tag: "7.4.11-alpine3.21"
  replicaCount: 1
  containerPort: 6379
  service:
    type: ClusterIP
    port: 6379
    targetPort: 6379
  probes:
    readiness:
      periodSeconds: 5
    liveness:
      periodSeconds: 5
  resources:
    requests:
      cpu: 70m
      memory: 200Mi
    limits:
      cpu: 125m
      memory: 256Mi

cartService:
  enabled: true
  image:
    name: cartservice
  replicaCount: 1
  containerPort: 7070
  service:
    type: ClusterIP
    port: 7070
    targetPort: 7070
  dependencies:
    redis: "redis-cart:6379"
  probes:
    readiness:
      initialDelaySeconds: 15
    liveness:
      initialDelaySeconds: 15
      periodSeconds: 10
  resources:
    requests:
      cpu: 200m
      memory: 64Mi
    limits:
      cpu: 300m
      memory: 128Mi

shippingService:
  enabled: true
  image:
    name: shippingservice
  replicaCount: 1
  containerPort: 50051
  service:
    type: ClusterIP
    port: 50051
    targetPort: 50051
  probes:
    readiness:
      periodSeconds: 5
    liveness:
      periodSeconds: 10
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

paymentService:
  enabled: true
  image:
    name: paymentservice
  replicaCount: 1
  containerPort: 50051
  service:
    type: ClusterIP
    port: 50051
    targetPort: 50051
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

emailService:
  enabled: true
  image:
    name: emailservice
  replicaCount: 1
  containerPort: 8080
  service:
    type: ClusterIP
    port: 5000
    targetPort: 8080
  probes:
    readiness:
      periodSeconds: 5
    liveness:
      periodSeconds: 5
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

checkoutService:
  enabled: true
  image:
    name: checkoutservice
  replicaCount: 1
  containerPort: 5050
  service:
    type: ClusterIP
    port: 5050
    targetPort: 5050
  dependencies:
    productCatalogService: "productcatalogservice:3550"
    shippingService: "shippingservice:50051"
    paymentService: "paymentservice:50051"
    emailService: "emailservice:5000"
    currencyService: "currencyservice:7000"
    cartService: "cartservice:7070"
  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
